{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "[PRD]CPU usage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cpu_usage_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[PRD]Memory usage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "memory_usage_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[PROD] Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "requests_total{requestType=\"PUT\", source=\"jwt-pizza-service\"}",
     "legendFormat": "PUT"
    },
    {
     "expr": "requests_total{requestType=\"POST\", source=\"jwt-pizza-service\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "requests_total{requestType=\"DELETE\", source=\"jwt-pizza-service\"}",
     "legendFormat": "DELETE"
    },
    {
     "expr": "requests_total{requestType=\"GET\", source=\"jwt-pizza-service\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(requests_total{source=\"jwt-pizza-service\"})",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "[DEV]CPU usage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[DEV]Memory usage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "memory_usage_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[DEV] Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "requests_total{requestType=\"PUT\", source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "PUT"
    },
    {
     "expr": "requests_total{requestType=\"POST\", source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "requests_total{requestType=\"DELETE\", source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "DELETE"
    },
    {
     "expr": "requests_total{requestType=\"GET\", source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(requests_total{source=\"jwt-pizza-service-dev\"})",
     "legendFormat": "TOTAL"
    }
   ]
  }
 ]
}